### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by bpaolo71** [FortnoxAB/csharp-api-sdk#192]
I get this error when I try to get a Supplier:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Fortnox.SDK.Connectors.Base.EntityConnector`1.<SendAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Fortnox.SDK.Connectors.Base.EntityConnector`1.<BaseGet>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Fortnox.SDK.Connectors.SupplierConnector.<GetAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Fortnox.SDK.Utility.TaskExtensions.GetResult[T](Task`1 task)
   at Fortnox.SDK.Connectors.SupplierConnector.Get(String id)

id is a valid supplierId that exists in Fortnox. I get this error only with one supplier.
I really don't understand why ! The version of SDK that i use is 4.1.0

**Comment by richardrandak** [comment]
Alternatively, could you get the supplier through postman and send me the JSON response? It is possible that the de-serialization failed.

**Comment by richardrandak** [comment]
That is a very weird behavior and it explains the error caused by de-serialization of empty response. This is something I can't solve. Please report the issue to the official Fortnox support and let us know about your findings.

**Comment by bpaolo71** [comment]
They answered me and this is really incredible :)
The VAT number was invalid! We were able to insert a supplier with a wrong VAT number by bypassing the validation but we cannot get it because the validation says that its is wrong :)
Support suggest to use PUT to update the VAT number but I get the error "System exception" so I asked them to do it otherwise i have to ask the customer to do it.

**Comment by richardrandak** [comment]
Hah, at least they help you to figure it out :)
Anyway, still don't get why server sends OK status.

**Comment by bpaolo71** [comment]
For what i can understand the server doesn't throw an exception but returns a null supplier :)
I think that they don't do the right thing but now should SDK manage it ?

**Comment by richardrandak** [comment]
In my opinion, it is a violation of the API contract, since OK response must come with the entity JSON payload.


Can you shown me how exactly the response looks like?

**Comment by bpaolo71** [comment]
I used Fiddler nu and just to show the difference I start with a supplier that works:
****
HTTP/1.1 200 OK
content-length: 896
content-type: application/json
date: Mon, 18 Oct 2021 12:08:21 GMT
vary: Accept-Encoding
x-build: 647b122d32
x-frame-options: sameorigin
x-rack-responsetime: 89
x-uid: a39944ec
server: Fortnox
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: strict-origin-when-cross-origin
content-security-policy: upgrade-insecure-requests;default-src 'none';child-src 'self' *.upsales.com *.findity.com *.fortnox.se data: *.livechatinc.com home.froda.se;connect-src 'self' *.fortnox.se wss://*.fortnox.se https:;font-src 'self' data: *.fortnox.se cdn.livechatinc.com themes.googleusercontent.com;frame-ancestors https://*.fortnox.se;frame-src 'self' *.upsales.com *.findity.com *.fortnox.se *.livechatinc.com home.froda.se blob: foretagslandirekt.aroskapital.se www.youtube-nocookie.com www.youtube.com;img-src 'self' blob: *.fortnox.se data: *.livechatinc.com *.zdusercontent.com;manifest-src 'self' *.fortnox.se;media-src *.fortnox.se;object-src blob: data: 'self' *.fortnox.se;script-src 'self' *.livechatinc.com *.fortnox.se 'unsafe-inline' 'unsafe-eval';style-src 'self' *.fortnox.se 'unsafe-eval' 'unsafe-inline';report-uri /api/cspreport
strict-transport-security: max-age=31536000; includeSubdomains

{"Supplier":{"@url":"https:\/\/api.fortnox.se\/3\/suppliers\/DT_1","Active":true,"Address1":"xxxxx","Address2":null ...
****
And now that doesn't work
****
HTTP/1.1 200 OK
content-length: 0
content-type: application/json
date: Mon, 18 Oct 2021 12:07:14 GMT
vary: Accept-Encoding
x-build: 647b122d32
x-frame-options: sameorigin
x-rack-responsetime: 161
x-uid: d5119c73
server: Fortnox
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: strict-origin-when-cross-origin
content-security-policy: upgrade-insecure-requests;default-src 'none';child-src 'self' *.upsales.com *.findity.com *.fortnox.se data: *.livechatinc.com home.froda.se;connect-src 'self' *.fortnox.se wss://*.fortnox.se https:;font-src 'self' data: *.fortnox.se cdn.livechatinc.com themes.googleusercontent.com;frame-ancestors https://*.fortnox.se;frame-src 'self' *.upsales.com *.findity.com *.fortnox.se *.livechatinc.com home.froda.se blob: foretagslandirekt.aroskapital.se www.youtube-nocookie.com www.youtube.com;img-src 'self' blob: *.fortnox.se data: *.livechatinc.com *.zdusercontent.com;manifest-src 'self' *.fortnox.se;media-src *.fortnox.se;object-src blob: data: 'self' *.fortnox.se;script-src 'self' *.livechatinc.com *.fortnox.se 'unsafe-inline' 'unsafe-eval';style-src 'self' *.fortnox.se 'unsafe-eval' 'unsafe-inline';report-uri /api/cspreport
strict-transport-security: max-age=31536000; includeSubdomains
****
There is not text !
