### ISSUE TITLE
Error converting value "FRX" to type 'System.Nullable`1[Fortnox.SDK.Entities.AbsenceCauseCode]'

### ISSUE THREAD

**Issue by jazzn3rd** [FortnoxAB/csharp-api-sdk#231]
In AbsenceCauseCode.cs
[https://github.com/FortnoxAB/csharp-api-sdk/blob/master/FortnoxSDK/Entities/Absence%20Transactions/AbsenceCauseCode.cs](url)

The enum does not handle FRX (Flextid)

Callstack:
```
Newtonsoft.Json.JsonSerializationException: Error converting value "FRX" to type 'System.Nullable`1[Fortnox.SDK.Entities.AbsenceCauseCode]'. Path 'AbsenceTransactions[1].CauseCode', line 1, position 426.
 ---> System.ArgumentException: Requested value 'FRX' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Fortnox.SDK.Serialization.JsonEntitySerializer.Deserialize[T](String json)
   at Fortnox.SDK.Connectors.Base.SearchableEntityConnector`3.GetSinglePage[T](SearchRequest`1 request)
   at Fortnox.SDK.Connectors.Base.SearchableEntityConnector`3.SendAsync[T](SearchRequest`1 request)
   at Fortnox.SDK.Connectors.Base.SearchableEntityConnector`3.BaseFind(BaseSearch searchSettings)
   at Fortnox.SDK.Connectors.AbsenceTransactionConnector.FindAsync(AbsenceTransactionSearch searchSettings)
```

**Comment by richardrandak** [comment]
The documentation specifies only these.. I don't see the FRX here. However, I can added to the enum.

![Screenshot_1](https://user-images.githubusercontent.com/58220739/154470350-c09e6e30-e5b1-4c91-bfda-b9a155fd0935.png)

**Comment by jazzn3rd** [comment]
I know. I also reacted to this. But if one sign in a Fortnox instance the
Cause Code is there. So they must have missed updating the documentation.



Den tors 17 feb. 2022 12:19richardrandak ***@***.***> skrev:

**Comment by richardrandak** [comment]
Update NuGet, the codes were added

**Comment by Snuffsis** [comment]
I would like to add that it is possible for users to add their own CauseCodes, in addition to all the existing ones that is mentioned in the documentation. So it would be better to change this to just a string, and not an enum, Or have some way to have it support these custom values as enum.

We have one that has created a bunch of their own causecodes. And this enum is making it so that quite a lot of transactions just doesn't appear. So we have had to create our own call for the Attendance/Absence transactions.
