### ISSUE TITLE
Failed to format date. Not given in any of the valid formats.

### ISSUE THREAD

**Issue by CaptainAweesome** [FortnoxAB/csharp-api-sdk#288]
The FromDate and ToDate parameter options don't work and returns an Api Exception.

```
await orderConnector.FindAsync(new  OrderSearch()
{
FromDate = DateTime.Now,
ToDate = DateTime.Now
});
```
```
Fortnox.SDK.Exceptions.FortnoxApiException: Request failed: Failed to format date. Not given in any of the valid formats.
   at Fortnox.SDK.Connectors.Base.ErrorHandler.HandleErrorResponseAsync(HttpResponseMessage response)
   at Fortnox.SDK.Connectors.Base.BaseClient.SendAsync(HttpRequestMessage request)
   at Fortnox.SDK.Connectors.Base.BaseConnector.SendAsync(BaseRequest fortnoxRequest)
   at Fortnox.SDK.Connectors.Base.SearchableEntityConnector`3.GetSinglePage[T](SearchRequest`1 request)
   at Fortnox.SDK.Connectors.Base.SearchableEntityConnector`3.SendAsync[T](SearchRequest`1 request)
   at Fortnox.SDK.Connectors.Base.SearchableEntityConnector`3.BaseFind(BaseSearch searchSettings)
   at Fortnox.SDK.Connectors.OrderConnector.FindAsync(OrderSearch searchSettings)
```

Reply from Fortnox Support:
Currently used url and parameters: `3/orders?fromdate=2024-01-01%2011%3A23%3A38&todate=2024-03-01%2011%3A23%3A38&page=1`
 
Using [3/orders/?fromdate=2024-01-01&todate=2024-03-01&page=1](https://api.fortnox.se/3/orders/?fromdate=2024-01-01&todate=2024-03-01&page=1) the error message will disappear.

Version 4.3.15 of Fortnox.NET.SDK

**Comment by adamelfstrom** [comment]
If you use dates without a timestamp (as shown in the second url) there should be no errors.

So, the following example should be working.
`FromDate = new DateTime(2024, 1, 1)`

Do you need to use timestamps in the search?
